project_id = "cgydeldzhnfyexphaheq"

[functions.chat-assistant]
verify_jwt = false

[functions.chat-uivo-lobo]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.populate-knowledge]
verify_jwt = false

[functions.sync-podcast-rss]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
