ALTER TABLE public.stage_photos
  ADD COLUMN IF NOT EXISTS focal_x numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS focal_y numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS zoom numeric NOT NULL DEFAULT 1;